name: "Push to Artifact Repo"
description: "Use bluehawk and bluehawk-plugin-git to copy, commit, and push transformed code to artifact repos."
inputs:
  name:
    description: "The name to use in the git commit."
    required: true
  email:
    description: "The email to use in the git commit."
    required: true
  toRepo:
    description: "The destination repo."
    required: true
  states:
    description: "A space-separated list of Bluehawk states to copy. Each state name becomes the destination branch name."
    required: false
  branch:
    description: "The destination branch name to use if 'states' is not provided."
    required: false
    default: main
  source:
    description: "The path to the source to copy."
    required: true
  commitMessage:
    description: "The commit message to use."
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
